name: Test package

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.10.15", "3.11", "3.12", "3.13"]
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --python ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest tests
